services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always

  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception
    restart: always

  mariadb:
      build: requirements/mariadb/.
      container_name: mariadb
      volumes:
        - mariadb:/var/lib/mysql
      env_file:
        - .env
      networks:
        - inception
      restart: always

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /var/www/html
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /var/lib/mysql
      o: bind
      type: none

networks:
  inception:
    driver: bridge