CREATE DATABASE IF NOT EXISTS inception_db;
DROP USER IF EXISTS 'jmarinho'@'%';
CREATE USER 'jmarinho'@'%' IDENTIFIED BY '123';
GRANT ALL PRIVILEGES ON *.* TO 'jmarinho'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
