services:
  nginx:
    build: srcs/nginx/.
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html

  wordpress:
    build: srcs/wordpress/.
    container_name: wp-php
    volumes:
      - ./web:/var/www/html