services:
    nginx:
        image: nginx:bookworm
        container_name: nginx
        hostname: nginx
        ports:
            - 80:80
        volumes:
            - ./volumes/nginx/conf/:/etc/nginx
            - ./volumes/nginx/html/:/usr/share/nginx/html
        networks:
            - inception-network
        restart: always
    
    wordpress:
        image: wordpress:beta-php8.3-fpm
        container_name: wordpress
        hostname: wordpress
        ports:
            - 8080:80
            - 9000:9000
        volumes:
            - ./volumes/wordpress/:/var/www/html
        environment:
            WORDPRESS_DB_HOST: mariadb
            WORDPRESS_DB_USER: dbuser
            WORDPRESS_DB_PASSWORD: dbpass
            WORDPRESS_DB_NAME: dbname
        networks:
            - inception-network
        restart: always

    db:
        image: mariadb:11.5.2
        container_name: db
        hostname: db
        environment:
            MARIADB_ROOT_PASSWORD: dbpass
        ports:
            - 3306:3306
        volumes:
            - ./volumes/mariadb/:/var/lib/mysql
        networks:
            - inception-network
        restart: always

    adminer:
        image: adminer:4.8.1-standalone
        ports:
            - 8081:8080
        networks:
            - inception-network
        restart: always

    redis:
        image: redis:bookworm
        container_name: redis
        hostname: redis
        ports:
            - 6379:6379
        command: redis-server --save 20 1 --loglevel warning --requirepass redispass
        volumes: 
            - ./volumes/redis/:/data
        networks:
            - inception-network
        restart: always

    ftpserver:
        image: fauria/vsftpd
        container_name: ftpserver
        hostname: ftpserver
        ports:
            - 21:21
            - 20:20
            - 21100-21110:21100-21110
        environment:
            FTP_USER: ftpuser 
            FTP_PASS: ftppass
            PASV_ADDRESS: 127.0.0.1
            PASV_MIN_PORT: 21100
            PASV_MAX_PORT: 21110
        volumes:
            - ./volumes/wordpress/:/home/vsftpd
        networks:
            - inception-network
        restart: always

networks:
    inception-network: