FROM debian:bullseye

# Install required dependencies and mariadb-server
RUN apt update -y && \
    apt upgrade -y && \
    apt install -y \
    mariadb-server

COPY 50-server.cnf /etc/mysql/mariadb.conf.d/.
COPY init.sql /etc/mysql/init.sql

RUN mkdir -p /run/mysqld

CMD ["mysqld"]